# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # This section defines a set of dependencies to check.
  - package-ecosystem: "pip"     # The package manager to use (e.g., "npm", "gomod", "maven").
    directory: "/"               # Location of package manifests (e.g., requirements.txt).
    schedule:
      interval: "daily"          # How often to check for updates ("weekly", "monthly").
    open-pull-requests-limit: 10 # A limit on how many PRs Dependabot can have open at once.
    reviewers:
      - "zkaiwen5810"
