# Generated by Django 5.0.14 on 2025-08-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EqDailyPx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(help_text="ticker, symbol or code", max_length=15),
                ),
                (
                    "trade_date",
                    models.DateField(help_text="Date of the trading session"),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=4, help_text="Opening price", max_digits=10
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price during the day",
                        max_digits=10,
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price during the day",
                        max_digits=10,
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=4, help_text="Closing price", max_digits=10
                    ),
                ),
                (
                    "prev_adj_close",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Previous adjusted close (for splits/dividends)",
                        max_digits=10,
                    ),
                ),
                (
                    "chg",
                    models.DecimalField(
                        decimal_places=4, help_text="Change in price", max_digits=10
                    ),
                ),
                (
                    "pct_chg",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Percentage change in price(based on previous day's close)",
                        max_digits=4,
                    ),
                ),
                (
                    "volume",
                    models.PositiveBigIntegerField(
                        help_text="Trading volume(in board lots)"
                    ),
                ),
                (
                    "turnover",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Turnover(in thousand RMB)",
                        max_digits=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of creation"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time of last update"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equity Daily Price",
                "verbose_name_plural": "Equity Daily Prices",
                "db_table": "eq_daily_px",
                "unique_together": {("ticker", "trade_date")},
            },
        ),
    ]
