# Generated by Django 5.0.14 on 2025-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dyor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EqBasic",
            fields=[
                (
                    "ticker",
                    models.CharField(
                        help_text="ticker, symbol or code",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stock Code or Security Code", max_length=10
                    ),
                ),
                ("name", models.CharField(help_text="Stock Name", max_length=100)),
                (
                    "area",
                    models.CharField(
                        blank=True, help_text="Region", max_length=50, null=True
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Industry", max_length=100, null=True
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        help_text="Full Stock Name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "enname",
                    models.CharField(
                        blank=True,
                        help_text="English Full Name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cnspell",
                    models.CharField(
                        blank=True,
                        help_text="Pinyin Abbreviation",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        blank=True,
                        help_text="Market Type (Main Board/ChiNext/STAR/CDR/BSE)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, help_text="Exchange Code", max_length=10, null=True
                    ),
                ),
                (
                    "curr_type",
                    models.CharField(
                        blank=True,
                        help_text="Trading Currency",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "list_status",
                    models.CharField(
                        blank=True,
                        help_text="Listing Status: L=Listed, D=Delisted, P=Suspended",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "list_date",
                    models.DateField(blank=True, help_text="Listing Date", null=True),
                ),
                (
                    "delist_date",
                    models.DateField(blank=True, help_text="Delisting Date", null=True),
                ),
                (
                    "is_hs",
                    models.CharField(
                        blank=True,
                        help_text="Shanghai-Shenzhen-Hong Kong Stock Connect: N=No, H=Shanghai Connect, S=Shenzhen Connect",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "act_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the Actual Controller",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "act_ent_type",
                    models.CharField(
                        blank=True,
                        help_text="Nature of the Actual Controller's Enterprise",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation Time"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Update Time"),
                ),
            ],
            options={
                "verbose_name": "Equity Basic Information",
                "verbose_name_plural": "Equity Basic Information",
                "db_table": "eq_basic",
                "ordering": ["ticker"],
                "indexes": [
                    models.Index(fields=["ticker"], name="eq_basic_ticker_6005d1_idx"),
                    models.Index(fields=["code"], name="eq_basic_code_6789a4_idx"),
                    models.Index(fields=["name"], name="eq_basic_name_e59e09_idx"),
                    models.Index(
                        fields=["industry"], name="eq_basic_industr_b571b5_idx"
                    ),
                    models.Index(fields=["market"], name="eq_basic_market_b26a75_idx"),
                ],
            },
        ),
    ]
